// Generated by CoffeeScript 1.8.0
(function() {
  var Bullet, lifetime, root, step_iterations;

  step_iterations = 5;

  lifetime = 0.8;

  Bullet = (function() {
    function Bullet(spq, spd) {
      var acceleration;
      this.texture = cofgl.game.textures.laser;
      this.inv = 1.0;
      acceleration = (function() {
        switch (cofgl.game.geometry.name) {
          case "euclidean":
            return 4.0;
          case "elliptic":
            return 15.0;
          case "hyperbolic":
            return 20.0;
        }
      })();
      this.q = new cofgl.Complex(spq.x, spq.y);
      this.dir = new cofgl.Complex(spd.x, spd.y);
      this.p = new cofgl.Complex(this.dir.x * acceleration, this.dir.y * acceleration);
      this.ts = 13.0;
      this.radius = 2 / this.ts;
      this.mass = 0.1;
      this.age = 0;
      this.faded = false;
    }

    Bullet.prototype.update = function(dt) {
      var i, _i, _ref;
      for (i = _i = 1; 1 <= step_iterations ? _i <= step_iterations : _i >= step_iterations; i = 1 <= step_iterations ? ++_i : --_i) {
        _ref = cofgl.game.geometry.step(this.q, this.p, this.dir, dt / step_iterations, this.inv), this.q = _ref[0], this.p = _ref[1], this.dir = _ref[2], this.inv = _ref[3];
      }
      this.dir = this.dir.plus(this.p);
      this.dir.normalize();
      this.age += dt;
      if (this.age >= lifetime) {
        return this.faded = true;
      }
    };

    return Bullet;

  })();

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.Bullet = Bullet;

}).call(this);
