// Generated by CoffeeScript 1.8.0
(function() {
  var FIRE_COOLDOWN, Game, MAX_FRAME, SHIELD_TIME, TICK, TOUCH_DEADZONE, captions, initEngineAndGame, keyMapping, loadBest, randomVelocity, removeWhere, root, saveBest;

  keyMapping = {
    40: 'brake',
    38: 'thrust',
    37: 'rotateLeft',
    39: 'rotateRight',
    83: 'brake',
    87: 'thrust',
    65: 'rotateLeft',
    68: 'rotateRight',
    32: 'fire'
  };

  TICK = 1 / 60;

  MAX_FRAME = 0.25;

  FIRE_COOLDOWN = 0.12;

  SHIELD_TIME = 1.5;

  TOUCH_DEADZONE = 20;

  removeWhere = function(array, pred) {
    var i;
    i = array.length;
    while (i--) {
      if (pred(array[i])) {
        array.splice(i, 1);
      }
    }
    return array;
  };

  randomVelocity = function(min, max) {
    var ang, speed;
    speed = min + Math.random() * (max - min);
    ang = Math.random() * 2 * Math.PI;
    return {
      x: speed * Math.cos(ang),
      y: speed * Math.sin(ang)
    };
  };

  captions = {
    euclidean: "Flat torus. Leave through one edge and you come back through the opposite one: edges of the same color are glued.",
    elliptic: "Projective plane, curvature +1. Antipodal points of the circle are glued (same colors). Crossing it mirrors you: the surface is non-orientable.",
    hyperbolic: "Genus-2 surface, curvature &minus;1. Opposite sides of the octagon (same colors) are glued; eight octagons meet at each corner."
  };

  loadBest = function(geometry) {
    var e;
    try {
      return parseInt(window.localStorage.getItem('nes-best-' + geometry), 10) || 0;
    } catch (_error) {
      e = _error;
      return 0;
    }
  };

  saveBest = function(geometry, score) {
    var e;
    try {
      return window.localStorage.setItem('nes-best-' + geometry, score);
    } catch (_error) {
      e = _error;
    }
  };

  Game = (function() {
    function Game() {
      this.keys = {};
      this.touches = {};
    }

    Game.prototype.initGame = function() {
      var gl, resources, texture;
      resources = cofgl.resmgr.resources;
      this.processor = new cofgl.Processor(resources['shaders/postprocess']);
      texture = function(name) {
        return cofgl.Texture.fromImage(resources[name], {
          mipmaps: true,
          filtering: 'LINEAR'
        });
      };
      this.textures = {
        spaceship: texture('space/spaceship'),
        asteroid: texture('space/asteroid'),
        bigAsteroid: texture('space/asteroid1'),
        laser: texture('space/laser')
      };
      this.geometries = {
        euclidean: {
          name: "euclidean",
          k: 0,
          shader: resources['shaders/euclidean'],
          step: cofgl.euclidTorusStep,
          distance: cofgl.torusDistance
        },
        elliptic: {
          name: "elliptic",
          k: 1,
          shader: resources['shaders/elliptic'],
          step: cofgl.kleinStep,
          distance: cofgl.projectiveDistance
        },
        hyperbolic: {
          name: "hyperbolic",
          k: -1,
          shader: resources['shaders/hyperbolic'],
          step: cofgl.poincareBitorusStep,
          distance: cofgl.bitorusDistance
        }
      };
      gl = cofgl.engine.gl;
      gl.disable(gl.DEPTH_TEST);
      this.world = new cofgl.World(this);
      return this.restart($("input[name='geometry']:checked").val());
    };

    Game.prototype.restart = function(geometry) {
      var _ref;
      this.geometry = (_ref = this.geometries[geometry]) != null ? _ref : this.geometries.euclidean;
      this.spaceShip = new cofgl.SpaceShip();
      this.bullets = [];
      this.asteroids = [];
      this.time = 0;
      this.lastFireTime = -Infinity;
      this.best = loadBest(this.geometry.name);
      this.newRecord = false;
      this.state = 'playing';
      this.newWave();
      return $('#geocaption').html(captions[this.geometry.name]);
    };

    Game.prototype.initEventHandlers = function() {
      $(window).on('keydown', (function(_this) {
        return function(event) {
          return _this.onKeyDown(event);
        };
      })(this)).on('keyup', (function(_this) {
        return function(event) {
          return _this.onKeyUp(event);
        };
      })(this)).on('blur', (function(_this) {
        return function() {
          return _this.pause();
        };
      })(this));
      $('#composite').on('touchstart touchmove', (function(_this) {
        return function(event) {
          return _this.onTouch(event);
        };
      })(this)).on('touchend touchcancel', (function(_this) {
        return function(event) {
          return _this.onTouchEnd(event);
        };
      })(this));
      $("input[name='geometry']").on('change', function() {
        cofgl.game.restart(this.value);
        return this.blur();
      });
      this.showGluing = $('#showgluing').prop('checked');
      return $('#showgluing').on('change', function() {
        cofgl.game.showGluing = this.checked;
        return this.blur();
      });
    };

    Game.prototype.onKeyDown = function(event) {
      var action;
      switch (event.which) {
        case 80:
        case 27:
          this.togglePause();
          return false;
        case 13:
          if (this.state === 'gameover') {
            this.restart(this.geometry.name);
          }
          return false;
      }
      action = keyMapping[event.which];
      if (action != null) {
        this.keys[action] = true;
        return false;
      }
    };

    Game.prototype.onKeyUp = function(event) {
      var action;
      action = keyMapping[event.which];
      if (action != null) {
        this.keys[action] = false;
        return false;
      }
    };

    Game.prototype.onTouch = function(event) {
      var rect, t, touch, x, y, _i, _len, _ref;
      event.preventDefault();
      rect = event.currentTarget.getBoundingClientRect();
      _ref = event.originalEvent.changedTouches;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        x = t.clientX - rect.left;
        y = t.clientY - rect.top;
        touch = this.touches[t.identifier];
        if (touch != null) {
          touch.x = x;
          touch.y = y;
        } else if (event.type === 'touchstart') {
          if (this.state === 'gameover') {
            this.restart(this.geometry.name);
          } else if (this.state === 'paused') {
            this.state = 'playing';
          } else {
            this.touches[t.identifier] = {
              fire: x > rect.width / 2,
              x0: x,
              y0: y,
              x: x,
              y: y
            };
          }
        }
      }
      return false;
    };

    Game.prototype.onTouchEnd = function(event) {
      var t, _i, _len, _ref;
      event.preventDefault();
      _ref = event.originalEvent.changedTouches;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        delete this.touches[t.identifier];
      }
      return false;
    };

    Game.prototype.pause = function() {
      if (this.state === 'playing') {
        this.state = 'paused';
      }
      this.keys = {};
      return this.touches = {};
    };

    Game.prototype.togglePause = function() {
      if (this.state === 'paused') {
        return this.state = 'playing';
      } else {
        return this.pause();
      }
    };

    Game.prototype.currentActions = function() {
      var action, actions, dx, dy, held, id, t, _ref, _ref1;
      actions = {};
      _ref = this.keys;
      for (action in _ref) {
        held = _ref[action];
        actions[action] = held;
      }
      _ref1 = this.touches;
      for (id in _ref1) {
        t = _ref1[id];
        if (t.fire) {
          actions.fire = true;
        } else {
          dx = t.x - t.x0;
          dy = t.y - t.y0;
          if (dx < -TOUCH_DEADZONE) {
            actions.rotateLeft = true;
          }
          if (dx > TOUCH_DEADZONE) {
            actions.rotateRight = true;
          }
          if (dy < -TOUCH_DEADZONE) {
            actions.thrust = true;
          }
          if (dy > TOUCH_DEADZONE) {
            actions.brake = true;
          }
        }
      }
      return actions;
    };

    Game.prototype.run = function() {
      return cofgl.resmgr.wait((function(_this) {
        return function() {
          _this.initGame();
          _this.initEventHandlers();
          return _this.mainloop();
        };
      })(this));
    };

    Game.prototype.mainloop = function() {
      return cofgl.engine.mainloop((function(_this) {
        return function(dt) {
          _this.advance(Math.min(dt, MAX_FRAME));
          _this.render();
          _this.updateUI();
          return _this.compose();
        };
      })(this));
    };

    Game.prototype.advance = function(dt) {
      var i, n, _i, _results;
      if (this.state === 'paused') {
        return;
      }
      n = Math.ceil(dt / TICK);
      _results = [];
      for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
        _results.push(this.tick(dt / n));
      }
      return _results;
    };

    Game.prototype.tick = function(h) {
      var asteroid, bullet, _i, _j, _len, _len1, _ref, _ref1;
      this.time += h;
      _ref = this.asteroids;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        asteroid = _ref[_i];
        asteroid.update(h);
      }
      if (this.state === 'gameover') {
        return;
      }
      this.handleInput(h);
      _ref1 = this.bullets;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        bullet = _ref1[_j];
        bullet.update(h);
      }
      removeWhere(this.bullets, function(b) {
        return b.faded;
      });
      this.spaceShip.update(h);
      return this.checkCollisions();
    };

    Game.prototype.handleInput = function(h) {
      var actions;
      actions = this.currentActions();
      this.spaceShip.steer((actions.rotateLeft ? 1 : 0) - (actions.rotateRight ? 1 : 0), h);
      if (actions.thrust) {
        this.spaceShip.thrust(h);
      }
      if (actions.brake) {
        this.spaceShip.brake(h);
      }
      if (actions.fire) {
        return this.fire();
      }
    };

    Game.prototype.fire = function() {
      if (this.time - this.lastFireTime < FIRE_COOLDOWN) {
        return;
      }
      this.bullets.push(new cofgl.Bullet(this.spaceShip.q, this.spaceShip.dir));
      return this.lastFireTime = this.time;
    };

    Game.prototype.checkCollisions = function() {
      var a, asteroid, bullet, destroyed, distance, i, old, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _ref, _ref1, _ref2, _results;
      distance = this.geometry.distance;
      _ref = this.asteroids;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        asteroid = _ref[_i];
        _ref1 = this.bullets;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          bullet = _ref1[_j];
          if (!bullet.faded) {
            if (distance(asteroid.q, bullet.q) < asteroid.radius) {
              bullet.faded = true;
              asteroid.hp -= 1;
              this.spaceShip.score += 1;
              if (asteroid.hp <= 0) {
                this.spaceShip.score += 10;
                break;
              }
            }
          }
        }
      }
      removeWhere(this.bullets, function(b) {
        return b.faded;
      });
      destroyed = (function() {
        var _k, _len2, _ref2, _results;
        _ref2 = this.asteroids;
        _results = [];
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          a = _ref2[_k];
          if (a.hp <= 0) {
            _results.push(a);
          }
        }
        return _results;
      }).call(this);
      removeWhere(this.asteroids, function(a) {
        return a.hp <= 0;
      });
      for (_k = 0, _len2 = destroyed.length; _k < _len2; _k++) {
        old = destroyed[_k];
        if (old.initial) {
          for (i = _l = 1; _l <= 2; i = ++_l) {
            this.asteroids.push(new cofgl.Asteroid(old.q, randomVelocity(0.2, 0.45), false));
          }
        }
      }
      if (this.asteroids.length === 0) {
        this.newWave();
      }
      if (this.spaceShip.shield > 0) {
        return;
      }
      _ref2 = this.asteroids;
      _results = [];
      for (_m = 0, _len3 = _ref2.length; _m < _len3; _m++) {
        asteroid = _ref2[_m];
        if (distance(asteroid.q, this.spaceShip.q) < asteroid.radius + this.spaceShip.radius) {
          this.shipHit();
          break;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Game.prototype.shipHit = function() {
      this.spaceShip.hp -= 1;
      if (this.spaceShip.hp > 0) {
        return this.spaceShip.respawn(SHIELD_TIME);
      } else {
        return this.gameOver();
      }
    };

    Game.prototype.gameOver = function() {
      this.state = 'gameover';
      this.bullets.length = 0;
      if (this.spaceShip.score > this.best) {
        this.best = this.spaceShip.score;
        this.newRecord = true;
        return saveBest(this.geometry.name, this.best);
      }
    };

    Game.prototype.addAsteroid = function() {
      var randomQ;
      randomQ = {
        x: (Math.random() < .5 ? -1 : 1) * (Math.random() * 0.2 + 0.4),
        y: (Math.random() < .5 ? -1 : 1) * (Math.random() * 0.2 + 0.4)
      };
      return this.asteroids.push(new cofgl.Asteroid(randomQ, randomVelocity(0.15, 0.35), true));
    };

    Game.prototype.newWave = function() {
      var i, _i, _ref;
      this.spaceShip.wave = this.spaceShip.wave + 1;
      for (i = _i = 0, _ref = this.spaceShip.wave; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.addAsteroid();
      }
      if (this.spaceShip.wave > 1) {
        return this.spaceShip.shield = SHIELD_TIME;
      }
    };

    Game.prototype.render = function() {
      cofgl.clear();
      this.processor.push();
      this.world.draw();
      return this.processor.pop();
    };

    Game.prototype.compose = function() {
      var ctx;
      ctx = $('#composite')[0].getContext('2d');
      ctx.globalCompositeOperation = "source-over";
      ctx.drawImage($('#viewport')[0], 0, 0);
      return ctx.drawImage($('#gui')[0], 0, 0);
    };

    Game.prototype.updateUI = function() {
      var gui, guiCanvas, h, lines, w;
      guiCanvas = $('#gui')[0];
      gui = guiCanvas.getContext('2d');
      w = guiCanvas.width;
      h = guiCanvas.height;
      gui.clearRect(0, 0, w, h);
      if (this.showGluing) {
        cofgl.drawGluing(gui, this.geometry.name);
      }
      gui.globalAlpha = 0.9;
      gui.fillStyle = "#e0a458";
      gui.textBaseline = "alphabetic";
      gui.font = "bold 16px sans-serif";
      gui.textAlign = "left";
      gui.fillText("Lives: " + Math.max(this.spaceShip.hp, 0), 15, 25);
      gui.textAlign = "right";
      gui.fillText("Score: " + this.spaceShip.score, w - 15, 25);
      gui.font = "14px sans-serif";
      gui.fillText("Best: " + Math.max(this.best, this.spaceShip.score), w - 15, 45);
      gui.font = "bold 16px sans-serif";
      gui.fillText("Wave: " + this.spaceShip.wave, w - 15, h - 15);
      if (this.spaceShip.shield > 0 && this.state === 'playing') {
        gui.textAlign = "center";
        gui.fillStyle = "#7fc8ff";
        gui.fillText("Shield", w / 2, h - 15);
      }
      switch (this.state) {
        case 'paused':
          this.drawOverlay(gui, "PAUSED", ["Press P or tap to resume"]);
          break;
        case 'gameover':
          lines = ["Score: " + this.spaceShip.score];
          lines.push(this.newRecord ? "New record!" : "Best: " + this.best);
          lines.push("Press Enter or tap to play again");
          this.drawOverlay(gui, "GAME OVER", lines);
      }
      return gui.globalAlpha = 1.0;
    };

    Game.prototype.drawOverlay = function(gui, title, lines) {
      var h, i, line, w, _i, _len, _results;
      w = gui.canvas.width;
      h = gui.canvas.height;
      gui.globalAlpha = 0.6;
      gui.fillStyle = "#000";
      gui.fillRect(0, h / 2 - 70, w, 30 * lines.length + 90);
      gui.globalAlpha = 1.0;
      gui.textAlign = "center";
      gui.fillStyle = "#e0a458";
      gui.font = "bold 36px sans-serif";
      gui.fillText(title, w / 2, h / 2 - 20);
      gui.fillStyle = "#ddd";
      gui.font = "18px sans-serif";
      _results = [];
      for (i = _i = 0, _len = lines.length; _i < _len; i = ++_i) {
        line = lines[i];
        _results.push(gui.fillText(line, w / 2, h / 2 + 20 + 30 * i));
      }
      return _results;
    };

    return Game;

  })();

  initEngineAndGame = function(selector, debug) {
    var canvas;
    canvas = $(selector)[0];
    if (!(window.WebGLRenderingContext && document.createElement('canvas').getContext('webgl'))) {
      $('.container').html("<p>Your browser could not initialize WebGL.<br>See " + "<a href='https://get.webgl.org'>get.webgl.org</a>.</p>");
      return;
    }
    cofgl.debugPanel = new cofgl.DebugPanel();
    cofgl.engine = new cofgl.Engine(canvas, debug);
    cofgl.resmgr = cofgl.makeDefaultResourceManager();
    cofgl.game = new Game;
    return cofgl.game.run();
  };

  $(document).ready(function() {
    var debug;
    debug = cofgl.getRuntimeParameter('debug') === '1';
    return initEngineAndGame('#viewport', debug);
  });

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.game = null;

  root.geometries = null;

  root.debugPanel = null;

  root.resmgr = null;

  root.engine = null;

}).call(this);
