// Generated by CoffeeScript 1.8.0
(function() {
  var arrowHead, drawBitorus, drawGluing, drawProjective, drawTorus, lineWidth, pairColors, root, toCanvas;

  pairColors = ['#e0a458', '#5fb3d9', '#9ad46a', '#e36d8e'];

  lineWidth = 4;

  toCanvas = function(ctx, x, y) {
    return [(x + 1) / 2 * ctx.canvas.width, (1 - y) / 2 * ctx.canvas.height];
  };

  arrowHead = function(ctx, x, y, angle, size) {
    if (size == null) {
      size = 9;
    }
    ctx.save();
    ctx.translate(x, y);
    ctx.rotate(angle);
    ctx.beginPath();
    ctx.moveTo(size, 0);
    ctx.lineTo(-size, -size * 0.8);
    ctx.lineTo(-size, size * 0.8);
    ctx.closePath();
    ctx.fill();
    return ctx.restore();
  };

  drawTorus = function(ctx) {
    var angle, arrows, color, edges, h, k, nx, ny, o, t, w, x0, x1, y0, y1, _i, _len, _ref, _ref1, _ref2, _results;
    w = ctx.canvas.width;
    h = ctx.canvas.height;
    o = lineWidth / 2;
    edges = [[pairColors[0], [o, h], [o, 0], 1], [pairColors[0], [w - o, h], [w - o, 0], 1], [pairColors[1], [0, h - o], [w, h - o], 2], [pairColors[1], [0, o], [w, o], 2]];
    _results = [];
    for (_i = 0, _len = edges.length; _i < _len; _i++) {
      _ref = edges[_i], color = _ref[0], (_ref1 = _ref[1], x0 = _ref1[0], y0 = _ref1[1]), (_ref2 = _ref[2], x1 = _ref2[0], y1 = _ref2[1]), arrows = _ref[3];
      ctx.strokeStyle = ctx.fillStyle = color;
      ctx.beginPath();
      ctx.moveTo(x0, y0);
      ctx.lineTo(x1, y1);
      ctx.stroke();
      angle = Math.atan2(y1 - y0, x1 - x0);
      nx = x0 === x1 ? (x0 < w / 2 ? 10 : -10) : 0;
      ny = y0 === y1 ? (y0 < h / 2 ? 10 : -10) : 0;
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (k = _j = 0; 0 <= arrows ? _j < arrows : _j > arrows; k = 0 <= arrows ? ++_j : --_j) {
          t = 0.5 + 0.035 * (k - (arrows - 1) / 2) * 2;
          _results1.push(arrowHead(ctx, x0 + t * (x1 - x0) + nx, y0 + t * (y1 - y0) + ny, angle));
        }
        return _results1;
      })());
    }
    return _results;
  };

  drawProjective = function(ctx) {
    var a0, a1, cx, cy, i, n, r, _i, _ref, _results;
    _ref = toCanvas(ctx, 0, 0), cx = _ref[0], cy = _ref[1];
    r = ctx.canvas.width / 2 - lineWidth / 2;
    n = 96;
    _results = [];
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      a0 = 2 * Math.PI * i / n;
      a1 = 2 * Math.PI * (i + 1) / n;
      ctx.strokeStyle = "hsl(" + (Math.round(360 * 2 * i / n) % 360) + ", 65%, 60%)";
      ctx.beginPath();
      ctx.arc(cx, cy, r, a0, a1 + 0.01);
      _results.push(ctx.stroke());
    }
    return _results;
  };

  drawBitorus = function(ctx) {
    var C, R, a0, a1, cx, cy, d, i, phi, rv, scale, th, x0, x1, y0, y1, _i, _ref, _ref1, _ref2, _ref3, _results;
    _ref = cofgl.octagonGeometry, C = _ref.C, R = _ref.R;
    scale = ctx.canvas.width / 2;
    phi = Math.PI / 8;
    rv = C * Math.cos(phi) - Math.sqrt(R * R - C * C * Math.sin(phi) * Math.sin(phi));
    _results = [];
    for (i = _i = 0; _i < 8; i = ++_i) {
      th = i * Math.PI / 4;
      _ref1 = toCanvas(ctx, C * Math.cos(th), C * Math.sin(th)), cx = _ref1[0], cy = _ref1[1];
      _ref2 = toCanvas(ctx, rv * Math.cos(th - phi), rv * Math.sin(th - phi)), x0 = _ref2[0], y0 = _ref2[1];
      _ref3 = toCanvas(ctx, rv * Math.cos(th + phi), rv * Math.sin(th + phi)), x1 = _ref3[0], y1 = _ref3[1];
      a0 = Math.atan2(y0 - cy, x0 - cx);
      a1 = Math.atan2(y1 - cy, x1 - cx);
      d = a1 - a0;
      while (d > Math.PI) {
        d -= 2 * Math.PI;
      }
      while (d <= -Math.PI) {
        d += 2 * Math.PI;
      }
      ctx.strokeStyle = pairColors[i % 4];
      ctx.beginPath();
      ctx.arc(cx, cy, R * scale, a0, a1, d < 0);
      _results.push(ctx.stroke());
    }
    return _results;
  };

  drawGluing = function(ctx, geometry) {
    ctx.save();
    ctx.globalAlpha = 0.85;
    ctx.lineWidth = lineWidth;
    ctx.lineCap = 'butt';
    switch (geometry) {
      case 'euclidean':
        drawTorus(ctx);
        break;
      case 'elliptic':
        drawProjective(ctx);
        break;
      case 'hyperbolic':
        drawBitorus(ctx);
    }
    return ctx.restore();
  };

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.drawGluing = drawGluing;

}).call(this);
