// Generated by CoffeeScript 1.8.0
(function() {
  var autoShortenFilename, dirname, floatColorFromHex, joinFilename, nextPowerOfTwo, root;

  dirname = function(filename) {
    return filename.match(/^(.*\/)/)[1];
  };

  joinFilename = function(parentFile, file) {
    return dirname(parentFile) + file;
  };

  autoShortenFilename = function(filename) {
    var base;
    base = dirname(document.baseURI);
    if (filename.substr(0, base.length) === base) {
      filename = filename.substr(base.length);
    }
    return filename;
  };

  floatColorFromHex = function(hex) {
    var a, b, g, r, _ref;
    if (hex.match(/^#/)) {
      hex = hex.substr(1);
    }
    a = 1.0;
    if ((_ref = hex.length) === 3 || _ref === 4) {
      r = parseInt(hex[0], 16) / 15.0;
      g = parseInt(hex[1], 16) / 15.0;
      b = parseInt(hex[2], 16) / 15.0;
      if (hex.length > 4) {
        a = parseInt(hex[3], 16) / 15.0;
      }
    } else {
      r = parseInt(hex.substr(0, 2), 16) / 255.0;
      g = parseInt(hex.substr(2, 2), 16) / 255.0;
      b = parseInt(hex.substr(4, 2), 16) / 255.0;
      if (hex.length > 6) {
        a = parseInt(hex.susbstr(6, 2), 16) / 255.0;
      }
    }
    return vec4.create([r, g, b, a]);
  };

  nextPowerOfTwo = function(value) {
    value--;
    value |= value >> 1;
    value |= value >> 2;
    value |= value >> 4;
    value |= value >> 8;
    value |= value >> 16;
    return value + 1;
  };

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.dirname = dirname;

  root.joinFilename = joinFilename;

  root.autoShortenFilename = autoShortenFilename;

  root.floatColorFromHex = floatColorFromHex;

  root.nextPowerOfTwo = nextPowerOfTwo;

}).call(this);
