// Generated by CoffeeScript 1.8.0
(function() {
  var RESOURCES, makeDefaultResourceManager, root;

  RESOURCES = [['shaders/hyperbolic', 'assets/shaders/hyperbolic.glsl'], ['shaders/hyperbolic_bg', 'assets/shaders/hyperbolic_bg.glsl'], ['shaders/elliptic', 'assets/shaders/elliptic.glsl'], ['shaders/euclidean', 'assets/shaders/euclidean.glsl'], ['shaders/postprocess', '../assets/shaders/postprocess.glsl'], ['shaders/nothing', '../assets/shaders/nothing.glsl'], ['shaders/starfield', 'assets/shaders/starfield.glsl'], ['space/asteroid', 'assets/textures/bwAst.png'], ['space/asteroid1', 'assets/textures/roundAst.png'], ['space/laser', 'assets/textures/laser.png'], ['space/spaceship', 'assets/textures/spaceship.png'], ['space/2spaceship', 'assets/textures/2spaceship.png'], ['space/spaceship', 'assets/textures/spaceship.png']];

  makeDefaultResourceManager = function() {
    var resmgr;
    resmgr = new cofgl.ResourceManager;
    resmgr.addFromList(RESOURCES);
    return resmgr;
  };

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.makeDefaultResourceManager = makeDefaultResourceManager;

}).call(this);
