// Generated by CoffeeScript 1.8.0
(function() {
  var SpaceShip, max_turn, max_vel, root, step_iterations, turn_accel, turn_damping;

  step_iterations = 5;

  max_vel = 5;

  max_turn = 4.5;

  turn_accel = 40.0;

  turn_damping = 25.0;

  SpaceShip = (function() {
    function SpaceShip() {
      this.texture = cofgl.game.textures.spaceship;
      this.inv = 1.0;
      this.q = new cofgl.Complex(0.0, 0.0);
      this.p = new cofgl.Complex(0.0, 0.0);
      this.dir = new cofgl.Complex(1.0, 0.0);
      this.turnVel = 0;
      this.ts = 13.0;
      this.radius = 2 / this.ts;
      this.mass = 10;
      this.hp = 3;
      this.score = 0;
      this.wave = 0;
      this.shield = 0;
      this.dec = 0.98;
      this.brakeDec = 0.9;
      this.thrustAccel = 6.0;
    }

    SpaceShip.prototype.steer = function(input, dt) {
      var ang, rot;
      if (input !== 0) {
        this.turnVel += input * turn_accel * dt;
        this.turnVel = Math.max(-max_turn, Math.min(max_turn, this.turnVel));
      }
      if (input === 0 || input * this.turnVel < 0) {
        this.turnVel *= Math.exp(-turn_damping * dt);
      }
      ang = this.turnVel * dt;
      rot = new cofgl.Complex(Math.cos(ang), Math.sin(ang));
      this.p = this.p.times(rot);
      return this.dir = this.dir.times(rot);
    };

    SpaceShip.prototype.update = function(dt) {
      var dec, i, _i, _ref;
      for (i = _i = 1; 1 <= step_iterations ? _i <= step_iterations : _i >= step_iterations; i = 1 <= step_iterations ? ++_i : --_i) {
        _ref = cofgl.game.geometry.step(this.q, this.p, this.dir, dt / step_iterations, this.inv), this.q = _ref[0], this.p = _ref[1], this.dir = _ref[2], this.inv = _ref[3];
      }
      this.dir = this.dir.plus(this.p);
      this.dir.normalize();
      dec = Math.pow(this.dec, 60 * dt);
      this.p.x = this.p.x * dec;
      this.p.y = this.p.y * dec;
      return this.shield = Math.max(0, this.shield - dt);
    };

    SpaceShip.prototype.thrust = function(dt) {
      var v;
      v = new cofgl.Complex(this.dir.x * this.thrustAccel * dt, this.dir.y * this.thrustAccel * dt);
      this.p = this.p.plus(v);
      if (this.p.y > max_vel) {
        this.p.y = max_vel;
      }
      if (this.p.x > max_vel) {
        this.p.x = max_vel;
      }
      if (this.p.y < -max_vel) {
        this.p.y = -max_vel;
      }
      if (this.p.x < -max_vel) {
        return this.p.x = -max_vel;
      }
    };

    SpaceShip.prototype.brake = function(dt) {
      var dec;
      dec = Math.pow(this.brakeDec, 60 * dt);
      return this.p = new cofgl.Complex(this.p.x * dec, this.p.y * dec);
    };

    SpaceShip.prototype.respawn = function(shieldTime) {
      this.q = new cofgl.Complex(0.0, 0.0);
      this.p = new cofgl.Complex(0.0, 0.0);
      this.inv = 1.0;
      return this.shield = shieldTime;
    };

    return SpaceShip;

  })();

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.SpaceShip = SpaceShip;

}).call(this);
