// Generated by CoffeeScript 1.8.0
(function() {
  var SpaceShip, max_vel, root, step_iterations;

  step_iterations = 5;

  max_vel = 5;

  SpaceShip = (function() {
    function SpaceShip() {
      var ang, angTouch;
      this.texture = cofgl.Texture.fromImage(cofgl.resmgr.resources['space/spaceship'], {
        mipmaps: true,
        filtering: 'LINEAR'
      });
      this.inv = 1.0;
      this.q = new cofgl.Complex(0.0, 0.0);
      this.p = new cofgl.Complex(0.0, 0.0);
      this.dir = new cofgl.Complex(1.0, 0.0);
      ang = Math.PI / 180 * 5;
      this.left = new cofgl.Complex(Math.cos(ang), Math.sin(ang));
      this.right = new cofgl.Complex(Math.cos(-ang), Math.sin(-ang));
      angTouch = Math.PI / 180 * 20;
      this.leftTouch = new cofgl.Complex(Math.cos(angTouch), Math.sin(angTouch));
      this.rightTouch = new cofgl.Complex(Math.cos(-angTouch), Math.sin(-angTouch));
      this.ts = 13.0;
      this.radius = 2 / this.ts;
      this.mass = 10;
      this.hp = 3;
      this.score = 0;
      this.wave = 0;
      this.hit = false;
      this.lastBulletTime = 0;
      this.bulletsUsed = 0;
      this.bulletCooldown = 100;
      this.dec = 0.98;
      this.cSides = [10.0, 10.0];
    }

    SpaceShip.prototype.update = function(dt) {
      var i, _i, _ref;
      for (i = _i = 1; 1 <= step_iterations ? _i <= step_iterations : _i >= step_iterations; i = 1 <= step_iterations ? ++_i : --_i) {
        _ref = cofgl.game.geometry.step(this.q, this.p, this.dir, dt / step_iterations, this.inv, this.cSides), this.q = _ref[0], this.p = _ref[1], this.dir = _ref[2], this.inv = _ref[3], this.cSides = _ref[4];
      }
      this.dir = this.dir.plus(this.p);
      this.dir.normalize();
      this.p.x = this.p.x * this.dec;
      return this.p.y = this.p.y * this.dec;
    };

    SpaceShip.prototype.rotateLeft = function() {
      this.p = this.p.times(this.left);
      return this.dir = this.dir.times(this.left);
    };

    SpaceShip.prototype.rotateRight = function() {
      this.p = this.p.times(this.right);
      return this.dir = this.dir.times(this.right);
    };

    SpaceShip.prototype.thurst = function() {
      var v;
      v = new cofgl.Complex(this.dir.x / 10.0, this.dir.y / 10.0);
      this.p = this.p.plus(v);
      if (this.p.y > max_vel) {
        this.p.y = max_vel;
      }
      if (this.p.x > max_vel) {
        this.p.x = max_vel;
      }
      if (this.p.y < -max_vel) {
        this.p.y = -max_vel;
      }
      if (this.p.x < -max_vel) {
        return this.p.x = -max_vel;
      }
    };

    SpaceShip.prototype["break"] = function() {
      var v;
      v = new cofgl.Complex(-this.dir.x / 10.0, -this.dir.y / 10.0);
      return this.p = this.p.plus(v);
    };

    SpaceShip.prototype.swipeLeft = function() {
      this.p = this.p.times(this.leftTouch);
      return this.dir = this.dir.times(this.leftTouch);
    };

    SpaceShip.prototype.swipeRight = function() {
      this.p = this.p.times(this.rightTouch);
      return this.dir = this.dir.times(this.rightTouch);
    };

    SpaceShip.prototype.swipeThurst = function() {
      var v;
      v = new cofgl.Complex(this.dir.x * 3.0, this.dir.y * 3.0);
      this.p = this.p.plus(v);
      if (this.p.y > max_vel) {
        this.p.y = max_vel;
      }
      if (this.p.x > max_vel) {
        this.p.x = max_vel;
      }
      if (this.p.y < -max_vel) {
        this.p.y = -max_vel;
      }
      if (this.p.x < -max_vel) {
        return this.p.x = -max_vel;
      }
    };

    SpaceShip.prototype.swipeBreak = function() {
      var v;
      v = new cofgl.Complex(-(this.dir.x * 3.0), -(this.dir.y * 3.0));
      return this.p = this.p.plus(v);
    };

    SpaceShip.prototype.hitShield = function() {
      var self;
      self = this;
      this.q = new cofgl.Complex(0.0, 0.0);
      this.p = new cofgl.Complex(0.0, 0.0);
      return setTimeout(function() {
        return self.hit = false;
      }, 1500);
    };

    return SpaceShip;

  })();

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.SpaceShip = SpaceShip;

}).call(this);
