// Generated by CoffeeScript 1.8.0
(function() {
  var C, R, bitorusDistance, diskDistance, dist, euclidStep, euclidTorusStep, j, kleinStep, l, octagon, octagonGluing, octagonInversion, octagonReflection, poincareBitorusStep, poincareStep, projectiveDistance, root, solveSystem, sqr2, sqr4, torusDistance;

  sqr2 = Math.sqrt(2.0);

  sqr4 = Math.sqrt(sqr2);

  l = (sqr4 + 1.0 / sqr4) / 2.0;

  C = l / Math.cos(Math.PI / 8.0);

  R = C * Math.tan(Math.PI / 8.0);

  octagon = [new cofgl.Complex(C, 0.0), new cofgl.Complex(C / sqr2, C / sqr2), new cofgl.Complex(0.0, C), new cofgl.Complex(-C / sqr2, C / sqr2), new cofgl.Complex(-C, 0.0), new cofgl.Complex(-C / sqr2, -C / sqr2), new cofgl.Complex(0.0, -C), new cofgl.Complex(C / sqr2, -C / sqr2)];

  octagonReflection = [new cofgl.ReflectionOrigin(new cofgl.Complex(0, 1)), new cofgl.ReflectionOrigin(new cofgl.Complex(-1, 1)), new cofgl.ReflectionOrigin(new cofgl.Complex(1, 0)), new cofgl.ReflectionOrigin(new cofgl.Complex(1, 1)), new cofgl.ReflectionOrigin(new cofgl.Complex(0, 1)), new cofgl.ReflectionOrigin(new cofgl.Complex(-1, 1)), new cofgl.ReflectionOrigin(new cofgl.Complex(1, 0)), new cofgl.ReflectionOrigin(new cofgl.Complex(1, 1))];

  octagonGluing = [4, 5, 6, 7, 0, 1, 2, 3];

  octagonInversion = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = octagonGluing.length; _i < _len; _i++) {
      j = octagonGluing[_i];
      _results.push(new cofgl.Inversion(octagon[j], R));
    }
    return _results;
  })();


  /*
  octagonReflection = [
    new cofgl.ReflectionOrigin(new cofgl.Complex(1,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(0,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(1,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(0,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(1,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(0,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(1,1)),
    new cofgl.ReflectionOrigin(new cofgl.Complex(0,1))
  ]
  
  octagonGluing = [2, 3, 0, 1, 6, 7, 4, 5]
   */

  solveSystem = function(a, b, c, d, f) {
    var b2, delta, den, g, h, p1, p2, sqdelta;
    b2 = b * b;
    g = a * f - c * d;
    h = a * c + d * f;
    den = 2.0 * b2 * (c * c + f * f);
    delta = b2 * (b2 * b2 - 4.0 * g * g - 4.0 * b2 * h);
    sqdelta = Math.sqrt(delta);
    p1 = b2 * b * c + 2.0 * b * f * g;
    p2 = b2 * b * f - 2.0 * b * c * g;
    switch (false) {
      case c === 0.0:
        return [(p1 - c * sqdelta) / den, (p2 - f * sqdelta) / den, (p1 + c * sqdelta) / den, (p2 + f * sqdelta) / den];
      default:
        if (f === 0.0) {
          return [a / b, d / b, a / b, d / b];
        } else {
          return [a / b, (p2 - f * sqdelta) / den, a / b, (p2 + f * sqdelta) / den];
        }
    }
  };

  euclidStep = function(q, p, dir, h) {
    q.x = q.x + h * p.x / 2.0;
    q.y = q.y + h * p.y / 2.0;
    return [q, p, dir];
  };

  euclidTorusStep = function(q, p, dir, h, glued) {
    var _ref;
    _ref = euclidStep(q, p, dir, h), q = _ref[0], p = _ref[1], dir = _ref[2];
    if (q.x > 1.0) {
      q.x = q.x - 2.0;
    }
    if (q.x < -1.0) {
      q.x = q.x + 2.0;
    }
    if (q.y > 1.0) {
      q.y = q.y - 2.0;
    }
    if (q.y < -1.0) {
      q.y = q.y + 2.0;
    }
    return [q, p, dir, glued];
  };

  poincareStep = function(q, p, dir, h) {
    var D, D2h, a, b, c, d, dqx, dqy, f, _ref;
    D = 1.0 - q.x * q.x - q.y * q.y;
    D2h = D * D * h;
    a = D * D2h * p.x;
    b = 8.0 * D;
    c = 16.0 * q.x;
    d = D * D2h * p.y;
    f = 16.0 * q.y;
    _ref = solveSystem(a, b, c, d, f), dqx = _ref[0], dqy = _ref[1];
    q.x = q.x + dqx;
    q.y = q.y + dqy;
    p.x = 8.0 * dqx / D2h;
    p.y = 8.0 * dqy / D2h;
    return [q, p, dir];
  };

  kleinStep = function(q, p, dir, h, glued) {
    var D, D2h, a, b, c, d, dqx, dqy, dx, dy, f, n, n2, px, py, _ref;
    D = 1.0 + q.x * q.x + q.y * q.y;
    D2h = D * D * h;
    a = D * D2h * p.x;
    b = 8.0 * D;
    c = -16.0 * q.x;
    d = D * D2h * p.y;
    f = -16.0 * q.y;
    _ref = solveSystem(a, b, c, d, f), dqx = _ref[0], dqy = _ref[1];
    q.x = q.x + dqx;
    q.y = q.y + dqy;
    p.x = 8.0 * dqx / D2h;
    p.y = 8.0 * dqy / D2h;
    n = q.x * q.x + q.y * q.y;
    if (n > 1.0) {
      glued = glued * -1.0;
      n2 = n * n;
      a = (q.x * q.x - q.y * q.y) / n2;
      b = 2.0 * q.x * q.y / n2;
      c = b;
      d = -a;
      px = p.x * a + p.y * b;
      py = p.x * c + p.y * d;
      p.x = px;
      p.y = py;
      dx = dir.x * a + dir.y * b;
      dy = dir.x * c + dir.y * d;
      dir.x = dx;
      dir.y = dy;
      q = new cofgl.Complex(-q.x / n2, -q.y / n2);
    }
    return [q, p, dir, glued];
  };

  dist = function(a, b) {
    return Math.sqrt((a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.y - b.y));
  };

  poincareBitorusStep = function(q, p, dir, h, glued) {
    var c, i, inv, refl, _i, _len, _ref;
    _ref = poincareStep(q, p, dir, h), q = _ref[0], p = _ref[1], dir = _ref[2];
    for (i = _i = 0, _len = octagon.length; _i < _len; i = ++_i) {
      c = octagon[i];
      if (dist(q, c) < R) {
        refl = octagonReflection[i];
        p = refl.D(q, p);
        dir = refl.D(q, dir);
        q = refl.F(q);
        inv = octagonInversion[i];
        p = inv.D(q, p);
        dir = inv.D(q, dir);
        q = inv.F(q);
        break;
      }
    }
    return [q, p, dir, glued];
  };

  diskDistance = function(z1, z2, k) {
    var den, r;
    den = new cofgl.Complex(1.0 + k * (z1.x * z2.x + z1.y * z2.y), k * (z1.y * z2.x - z1.x * z2.y));
    r = Math.sqrt(z1.minus(z2).divide(den).magnitude);
    switch (k) {
      case -1:
        return 2.0 * Math.atanh(Math.min(r, 1.0 - 1e-12));
      case 0:
        return 2.0 * r;
      default:
        return 2.0 * Math.atan(r);
    }
  };

  torusDistance = function(z1, z2) {
    var d, ox, oy, _i, _j, _len, _len1, _ref, _ref1;
    d = Infinity;
    _ref = [-2.0, 0.0, 2.0];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ox = _ref[_i];
      _ref1 = [-2.0, 0.0, 2.0];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        oy = _ref1[_j];
        d = Math.min(d, diskDistance(z1, new cofgl.Complex(z2.x + ox, z2.y + oy), 0));
      }
    }
    return d;
  };

  projectiveDistance = function(z1, z2) {
    var d;
    d = diskDistance(z1, z2, 1);
    return Math.min(d, Math.PI - d);
  };

  bitorusDistance = function(z1, z2) {
    var d, i, refl, _i, _len;
    d = diskDistance(z1, z2, -1);
    for (i = _i = 0, _len = octagonReflection.length; _i < _len; i = ++_i) {
      refl = octagonReflection[i];
      d = Math.min(d, diskDistance(z1, octagonInversion[i].F(refl.F(z2)), -1));
    }
    return d;
  };

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.poincareStep = poincareStep;

  root.kleinStep = kleinStep;

  root.euclidStep = euclidStep;

  root.euclidTorusStep = euclidTorusStep;

  root.poincareBitorusStep = poincareBitorusStep;

  root.octagonGeometry = {
    C: C,
    R: R
  };

  root.torusDistance = torusDistance;

  root.projectiveDistance = projectiveDistance;

  root.bitorusDistance = bitorusDistance;

}).call(this);
