// Generated by CoffeeScript 1.8.0
(function() {
  var World, root;

  World = (function() {
    function World(game) {
      this.game = game;
      this.vbo = cofgl.makeQuadVBO();
      this.backgroundShader = cofgl.resmgr.resources['shaders/starfield'];
    }

    World.prototype.draw = function() {
      var asteroid, bullet, ship, _i, _j, _len, _len1, _ref, _ref1;
      cofgl.clear('#fff');
      cofgl.withContext([this.backgroundShader], (function(_this) {
        return function() {
          _this.backgroundShader.uniform1f("time", _this.game.time);
          _this.backgroundShader.uniform2f("resolution", cofgl.engine.width, cofgl.engine.height);
          return _this.vbo.draw();
        };
      })(this));
      _ref = this.game.asteroids;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        asteroid = _ref[_i];
        this.drawObject(asteroid);
      }
      _ref1 = this.game.bullets;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        bullet = _ref1[_j];
        this.drawObject(bullet);
      }
      ship = this.game.spaceShip;
      if (this.game.state !== 'gameover' && Math.floor(ship.shield * 8) % 2 === 0) {
        return this.drawObject(ship);
      }
    };

    World.prototype.drawObject = function(obj) {
      var shader;
      shader = this.game.geometry.shader;
      return cofgl.withContext([shader, obj.texture], (function(_this) {
        return function() {
          shader.uniform2f("uq", obj.q.x, obj.q.y);
          shader.uniform2f("up", obj.p.x, obj.p.y);
          shader.uniform2f("udir", obj.dir.x, obj.dir.y);
          shader.uniform1f("texSize", obj.ts);
          shader.uniform1f("inverted", obj.inv);
          return _this.vbo.draw();
        };
      })(this));
    };

    return World;

  })();

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.World = World;

}).call(this);
